#ifndef RESPONSECODES_H
#define RESPONSECODES_H

#include <QMessageBox>

typedef enum{
    SUCCESS,
    FILE_NAME_FAILURE,
    OPEN_FILE_FAILURE,
    EMPTY_FILE_FAILURE,
    CREATE_FILE_FAILURE,
    READ_FILE_FAILURE,
    WRITE_FILE_FAILURE,
    WRONG_COUNT_OF_POINTS_FAILURE,
    NO_POINTS_FAILURE,
    WRONG_POINTS_FAILURE,
    WRONG_COUNT_OF_LINKS_FAILURE,
    NO_LINKS_FAILURE,
    WRONG_LINKS_FAILURE,
    ALLOCATE_MEMORY_FAILURE,
    WRONG_SCENE_FAILURE,
    WRONG_MOVE_COEFFICIENTS,
    WRONG_SCALE_COEFFICIENTS,
    WRONG_TURN_COEFFICIENTS,
    UNDEFINED_ACTION
} response_code_t;

void failure_message(response_code_t error);

#endif // RESPONSECODES_H
